# Plugin Author - Mesharsky
# https://csowicze.pl/

# Team Balance Plugin Configuration
# Adjust these settings according to your server's needs.

[PluginSettings]

# Plugin's chat tag for messages in chat.
# Supported colors:
# [white], [darkred], [green], [lightyellow], [lightblue], [olive], [lime],
# [red], [lightpurple], [purple], [grey], [yellow], [gold], [silver], [blue],
# [darkblue], [bluegrey], [magenta], [lightred], [orange]
plugin_chat_tag = "{red}[TeamBalance]"

# Minimum number of players required on the server before team balance activates.
# Prevents balancing when there are too few players.
# Default: 4
minimum_players = 4

# Maximum allowed score ratio between teams before triggering a balance.
# For example, if set to 2.0, balancing will trigger if one team's score
# is 2 times greater than the other team's score.
# Default: 2.0
score_balance_ratio = 2.0

# Use PerformanceScore for balancing.
# PerformanceScore takes into account KDA (Kills, Deaths, Assists),
# damage dealt, and the in-game score to evaluate player performance.
# Default: true
use_performance_score = true

# Maximum allowed difference in team sizes after balancing.
# If set to 1, the teams will be balanced such that one team cannot have
# more than one extra player compared to the other.
# Default: 1
max_team_size_difference = 1

# Enable or disable debug messages.
# If true, debug messages will be printed to the server console.
# Default: true
enable_debug_messages = true

# Enable or disable chat messages.
# If true, messages will be sent to the chat.
# Default: true
enable_chat_messages = true

# Scramble Mode Configuration
# scramble_mode determines when and how teams are scrambled.
# Options: "none" (no scrambling), "round" (scramble every X rounds),
# "winstreak" (scramble after a team wins X rounds in a row),
# "halftime" (scramble at halftime).
# Default: "none"
scramble_mode = "none"

# Number of rounds after which teams should be scrambled (if scramble_mode is "round").
# Default: 5
round_scramble_interval = 5

# Number of consecutive wins to trigger a scramble (if scramble_mode is "winstreak").
# Default: 3
winstreak_scramble_threshold = 3

# Enable or disable halftime scrambling (if scramble_mode is "halftime").
# Default: false
halftime_scramble_enabled = false